FROM python:3.11-alpine

RUN apk add --update tzdata \
    && ln -snf /usr/share/zoneinfo/Europe/Moscow /etc/localtime \
    && echo Europe/Moscow > /etc/timezone

WORKDIR /app

COPY . .

RUN python -m pip --no-cache-dir install --upgrade pip \
    && python -m pip install --no-cache-dir -r requirements.txt